export { userReducer as user } from '../reducers/user'
export { guestReducer as guest } from '../reducers/guest'
export { weddingReducer as wedding } from '../reducers/wedding'
export { invitationReducer as invitation } from '../reducers/invitation'
export { commentReducer as comment } from '../reducers/comment'